# Generated by Django 4.0.3 on 2024-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('action', models.IntegerField()),
                ('q_value', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('state', 'action')},
            },
        ),
    ]
