# Generated by Django 4.0.3 on 2024-11-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qvalue',
            name='action',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='qvalue',
            name='state',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
