# Generated by Django 4.0.3 on 2025-01-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_qtr_points',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_qtr_points',
        ),
    ]
