# Generated by Django 4.0.3 on 2025-01-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_remove_game_away_qtr_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(),
        ),
    ]
