# Generated by Django 4.0.3 on 2025-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_alter_game_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
