# Generated by Django 4.0.3 on 2024-10-19 21:41

import apps.treasure_hunt.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('object', models.ImageField(blank=True, null=True, upload_to=apps.treasure_hunt.models.treasure_location)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreasureHuntGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('treasures', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('is_started', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreasureHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('hint_img', models.ImageField(blank=True, null=True, upload_to=apps.treasure_hunt.models.treasure_hint_location)),
                ('hint', models.CharField(max_length=255)),
                ('requirement_for_hint', models.CharField(max_length=255)),
                ('treasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='treasure_hunt.treasure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTreasureHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Not activate'), (1, 'Processing'), (2, 'Activate')], default=0)),
                ('activate_evidence', models.ImageField(blank=True, null=True, upload_to=apps.treasure_hunt.models.group_treasure_hint_evidence_location)),
                ('activate_time', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_treasure_hint', to='treasure_hunt.group')),
                ('treasure_hint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_treasure_hint', to='treasure_hunt.treasurehint')),
            ],
            options={
                'unique_together': {('group', 'treasure_hint')},
            },
        ),
        migrations.CreateModel(
            name='GroupTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Not found'), (1, 'Processing'), (2, 'Found')], default=0)),
                ('found_evidence', models.ImageField(blank=True, null=True, upload_to=apps.treasure_hunt.models.group_treasure_evidence_location)),
                ('found_time', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_treasure', to='treasure_hunt.group')),
                ('treasure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_treasure', to='treasure_hunt.treasure')),
            ],
            options={
                'unique_together': {('group', 'treasure')},
            },
        ),
    ]
